addons:
  apt:
    packages:
      - automake
      - libtool
      - autoconf
      - flex
      - bison
      - gfortran
      - zlib1g-dev
      - libbz2-dev

compiler:
  - gcc
  - clang

script:
  - ./sync.bash

install:
  - ./sync.bash  
  - ./build.bash